version: '3.8'

services:
  pricepilot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERPAPI_KEY=${SERPAPI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped